app/site_mgt/urls.py
from django.urls import path
from .views import *

app_name = 'site_mgt'

urlpatterns = [
    path('', home, name='home'),
    path('redirect_user', redirect_user, name='redirect_user'),
    path('estate_manager_dashboard', estate_manager_dashboard, name='estate_manager_dashboard'),
    path('resident_dashboard', tenant_dashboard, name='tenant_dashboard'),
    path('security_dashboard', security_dashboard, name='security_dashboard'),
    path('estate_members', estate_members, name='estate_members'),
    path('visitor_log', visitor_log, name='visitor_log'),
    path('add_member', add_member, name='add_member'),
    path('estate_visitors_log', estate_visitor_log, name='estate_visitor_log'),
    path('profile', profile, name='profile'),
    path('my_buildings', my_buildings, name='my_buildings'),
    path('my_estates', my_estates, name='my_estates'),
    path('my_streets', my_streets, name='my_streets'),
    path('my_apartments', my_apartments, name='my_apartments'),
    path('update_estate/<pk>/edit/', estate_edit, name='update_estate'),
    path('my_estates/<pk>/delete/', delete_estate, name='delete_estate'),
    path('update_street/<pk>/edit/', street_edit, name='update_street'),
    path('update_resident/<pk>/edit/', resident_edit, name='update_resident'),
    path('my_streets/<pk>/delete/', delete_street, name='delete_street'),
    path('update_building/<pk>/edit/', building_edit, name='update_building'),
    path('my_buildings/<pk>/delete/', delete_building, name='delete_building'),
    path('update_apartment/<pk>/edit/', apartment_edit, name='update_apartment'),
    path('my_apartments/<pk>/delete/', delete_apartment, name='delete_apartment'),
    path('estate_members/<pk>/delete/', delete_resident, name='delete_resident'),
    path('add_estate_manager', add_estate_manager, name='add_estate_manager'),
    path('get_details/', get_details, name='get_details'),
    path('get_details_apartment/', get_details_apartment, name='get_details_apartment'),
    path('profile_status/', profile_status, name='profile_status'),
    path('add_street/', add_street, name='add_street'),
    path('get_all_streets/', get_all_streets, name='get_all_streets'),
    path('add_building/', add_building, name='add_building'),
    path('add_apartment/', add_apartment, name='add_apartment'),
    path('userEstateReg/', userEstateReg, name='userEstateReg'),
    path('get_details_build/', get_details_build, name='get_details_build'),
    path('add_residents/', add_residents, name='add_residents'),
    # path('street_dashboard/', street_dashboard, name='street_dashboard'),
    # path('building_dashboard/', building_dashboard, name='building_dashboard'),
    # path('apartment_dashboard/', apartment_dashboard, name='apartment_dashboard'),
    path('salutation/', salutation, name='salutation'),
]

sump/urls.py
from django.contrib import admin
from django.urls import path,include
# This Imports are for serving media files
from django.conf import settings
from django.urls import re_path
from django.views.static import serve
from rest_framework import routers
from api.views import *
from rest_framework.documentation import include_docs_urls

# Routers provide an easy way of automatically determining the URL conf.
router = routers.DefaultRouter()
router.register(r'visitor', VisitorViewSet)
router.register(r'user', UserViewSet)
router.register(r'role', RoleViewSet)
router.register(r'estate', EstateViewSet)
router.register(r'login', LoginUserViewSet, base_name='login')


urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/v1/', include(router.urls)),
    path('acc/', include('app.user.urls')),
    path('', include('app.site_mgt.urls')),
    path('accounts/', include('registration.backends.default.urls')),
    path('api/v1/docs', include_docs_urls(title='Sump Backend API', public=False)),
]

urlpatterns += [
    re_path(
        r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT, }

    ),
]

templates/site/tenant/dashboard.html
{% extends "site/base.html" %}
{% load static %}

{% block content %}
<!--DashBoard Filler-->
            <!-- Page Title Area -->
            <div class="row page-title clearfix">
                <div class="page-title-left">
                    <h6 class="page-title-heading mr-0 mr-r-5">{{user.estate}}</h6>
                    <p class="page-title-description mr-0 d-none d-md-inline-block">| Dashboard</p>
                </div>
                <!-- /.page-title-left -->
                <div class="page-title-right d-none d-sm-inline-flex">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a href="index.html">Dashboard</a>
                        </li>
                        <li class="breadcrumb-item active">Home</li>
                    </ol>
                </div>
                <!-- /.page-title-right -->
            </div>
            <!-- /.page-title -->
            <!-- =================================== -->
            <!-- Different data widgets ============ -->
            <!-- =================================== -->
            <div class="widget-list row">
                <div class="widget-holder widget-sm col-md-3 widget-full-height">
                    <div class="widget-bg">
                        <div class="widget-body">
                            <div class="counter-w-info media">
                                <div class="media-body">
                                    <a href="{% url 'site_mgt:visitor_log' %}">
                                    <p class="text-muted mr-b-5">Visitors Invited</p><span class="counter-title color-primary"><span class="counter">{{estate_members}}</span> </span>

                                    <div class="mr-t-20"><span data-toggle="sparklines" data-height="15" data-width="70" data-line-color="#1976d2" data-line-width="3" data-spot-radius="1" data-fill-color="rgba(0,0,0,0)" data-spot-color="undefined" data-min-spot-color="undefined"
                                        data-max-spot-color="undefined" data-highlight-line-color="undefined"><!-- 10,5,7,8,3,0,4,12,10,8,12 --></span>
                                    </div>
                                    </a>
                                </div>
                                <!-- /.media-body -->

                                <div class="pull-right align-self-center"><a href="{% url 'site_mgt:visitor_log' %}"><i class="list-icon feather feather-user-plus bg-primary"></i>
                                </a></div>

                            </div>
                            <!-- /.counter-w-info -->
                        </div>
                        <!-- /.widget-body -->
                    </div>
                    <!-- /.widget-bg -->
                </div>
                <!-- /.widget-holder -->
                <div class="widget-holder widget-sm col-md-3 widget-full-height">
                    <div class="widget-bg">
                        <div class="widget-body">
                            <div class="counter-w-info media">
                                <div class="media-body">
                                    <p class="text-muted mr-b-5">Repair Request</p><span class="counter-title color-info"><span class="counter">58</span>%</span>
                                    <!-- /.counter-title --> <span class="counter-difference text-danger"><i class="feather feather-user-plus"></i> 8%</span>
                                    <div class="progress" style="width: 70%; position: relative; top: 25px">
                                        <div class="progress-bar bg-info" style="width: 66%" role="progressbar"><span class="sr-only">20% Complete</span>
                                        </div>
                                    </div>
                                </div>
                                <!-- /.media-body -->
                                <div class="pull-right align-self-center"><i class="list-icon feather feather-user-plus bg-info"></i>
                                </div>
                            </div>
                            <!-- /.counter-w-info -->
                        </div>
                        <!-- /.widget-body -->
                    </div>
                    <!-- /.widget-bg -->
                </div>
                <!-- /.widget-holder -->
                <div class="widget-holder widget-sm col-md-3 widget-full-height">
                    <div class="widget-bg">
                        <div class="widget-body">
                            <div class="counter-w-info media">
                                <div class="media-body">
                                    <p class="text-muted mr-b-5">Emergency Reports</p></span>
                                    <!-- /.counter-title -->
                                    <div style="margin-top: 15px"><span data-toggle="sparklines" data-height="15" data-bar-width="3" data-type="bar" data-chart-range-min="0" data-bar-spacing="3" data-bar-color="#ff6b88"><!-- 2,4,5,3,2,3,5,3,2,3,5,4,2 --></span>
                                    </div>
                                </div>
                                <!-- /.media-body -->
                                <div class="pull-right align-self-center"><i class="list-icon feather feather-x-circle bg-danger"></i>
                                </div>
                            </div>
                            <!-- /.counter-w-info -->
                        </div>
                        <!-- /.widget-body -->
                    </div>
                    <!-- /.widget-bg -->
                </div>
                <!-- /.widget-holder -->
                <div class="widget-holder widget-sm col-md-3 widget-full-height">
                    <div class="widget-bg">
                        <div class="widget-body">
                            <div class="counter-w-info media">
                                <div class="media-body">
                                    <p class="text-muted mr-b-5">Utility Payment</p><span class="counter-title"></span>
                                    <div style="margin-top: 15px"><span data-toggle="sparklines" data-height="15" data-bar-width="3" data-type="bar" data-chart-range-min="0" data-bar-spacing="3" data-bar-color="#008000"><!-- 2,4,5,3,2,3,5,3,2,3,5,4,2 --></span>
                                    </div>
                                    <!-- /.counter-title -->

                                </div>
                                <!-- /.media-body -->
                                <div class="pull-right align-self-center"><i class="list-icon feather feather-clock bg-green"></i>
                                </div>
                            </div>
                            <!-- /.counter-w-info -->
                        </div>
                        <!-- /.widget-body -->
                    </div>
                    <!-- /.widget-bg -->
                </div>

            </div>
            <!-- /.widget-list -->
            <hr>

            <!-- /.widget-list -->

{% endblock %}