app/user/urls.py
from django.urls import path
from django.contrib.auth import views
from .views import *

app_name = 'user'

urlpatterns = [
    path('accounts/signup', RegisterView.as_view(), name='register'),
    path('test', test, name='test'),
    path('logout', logout_view, name='logout'),
    # path('login', login_view, name='login'),

]

sump/urls.py
from django.contrib import admin
from django.urls import path,include
# This Imports are for serving media files
from django.conf import settings
from django.urls import re_path
from django.views.static import serve
from rest_framework import routers
from api.views import *
from rest_framework.documentation import include_docs_urls

# Routers provide an easy way of automatically determining the URL conf.
router = routers.DefaultRouter()
router.register(r'visitor', VisitorViewSet)
router.register(r'user', UserViewSet)
router.register(r'role', RoleViewSet)
router.register(r'estate', EstateViewSet)
router.register(r'login', LoginUserViewSet, base_name='login')


urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/v1/', include(router.urls)),
    path('acc/', include('app.user.urls')),
    path('', include('app.site_mgt.urls')),
    path('accounts/', include('registration.backends.default.urls')),
    path('api/v1/docs', include_docs_urls(title='Sump Backend API', public=False)),
]

urlpatterns += [
    re_path(
        r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT, }

    ),
]

templates/site/home.html
<!doctype html>
{% load static %}
<!--[if lt IE 7]>      <html lang="en" class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html lang="en" class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html lang="en" class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!-->
<html lang="zxx" class="no-js">
<!--<![endif]-->

<head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- ======= titles ======= -->
    <title>{{site_name}}</title>
    <meta name="description" content="Automate your Estate Operations now with Clannit">
    <meta name="keywords" content="estate, estate managemnet solutions, solutions for estates">
    <meta name="author" content="clannit">
    <!-- ======= favicon ======= -->
    <link rel="icon" type="image/png" href="favicon.png">
    <!-- ======= Google Fonts ======= -->
    <link href="https://fonts.googleapis.com/css?family=Poppins:300,400,500,600,700" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Shadows+Into+Light" rel="stylesheet">
    <!-- ======= All CSS ======= -->
    <!-- bootstrap css -->
    <link rel="stylesheet" href="{% static 'site/home_page/css/bootstrap.min.css' %}">
    <!-- font-awesome css -->
    <link rel="stylesheet" href="{% static 'site/home_page/css/font-awesome.min.css' %}">
    <!-- owl carousel css -->
    <link rel="stylesheet" href="{% static 'site/home_page/css/owl.carousel.min.css' %}">
    <!-- animate css -->
    <link rel="stylesheet" href="{% static 'site/home_page/css/animate.css' %}">
    <!-- vegas css -->
    <link rel="stylesheet" href="{% static 'site/home_page/css/vegas.min.css' %}">
    <!-- hover css -->
    <link rel="stylesheet" href="{% static 'site/home_page/css/hover.css' %}">
    <!-- typing css -->
    <link rel="stylesheet" href="{% static 'site/home_page/css/typing.css' %}">
    <!-- lightbox css -->
    <link rel="stylesheet" href="{% static 'site/home_page/css/lightbox.min.css' %}">
    <!-- normalize css -->
    <link rel="stylesheet" href="{% static 'site/home_page/css/normalize.css' %}">
    <!-- main css -->
    <link rel="stylesheet" href="{% static 'site/home_page/css/main.css' %}">
    <!-- responsive css -->
    <link rel="stylesheet" href="{% static 'site/home_page/css/responsive.css' %}">
</head>

<body data-spy="scroll" data-target=".navbar">
    <!--[if lte IE 9]>
        <p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="https://browsehappy.com/">upgrade your browser</a> to improve your experience and security.</p>
    <![endif]-->

    <!-- ======= preloader part start ======= -->
    <div class="preloader">
        <div class="spinner">
            <div class="double-bounce1"></div>
            <div class="double-bounce2"></div>
        </div>
    </div>
    <!-- ======= preloader Part end ======= -->

    <!-- ======= Header Part Start ======= -->
    <header class="header-area navbar-fixed-top">
        <div class="container">
            <div class="row">
                <div class="col-md-5 col-xs-5">
                    <!-- logo part -->
                    <div class="">
                        <img width="200px !important" src="{% static 'site/asset/img/133.png' %}">
                    </div>
                </div>
                <div class="col-md-7 col-xs-7">
                    <!-- menu part -->
                    <div class="menu-part">
                        <nav class="navbar navbar-default">
                            <div class="container-fluid">
                                <!-- Brand and toggle get grouped for better mobile display -->
                                <div class="navbar-header">
                                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                                    <span class="sr-only">Toggle navigation</span>
                                    <span class="icon-bar"></span>
                                    <span class="icon-bar"></span>
                                    <span class="icon-bar"></span>
                                  </button>
                                </div>
                                <!-- Collect the nav links, forms, and other content for toggling -->
                                <div class="collapse navbar-collapse main-menu" id="bs-example-navbar-collapse-1">
                                    <ul class="nav navbar-nav">
                                        <li class="active"><a class="nav-link" href="#top">home</a></li>
                                        <li><a  href="http://clanit.herokuapp.com/clannit.apk"> Download Mobile App</a></li>
                                    </ul>
                                </div>
                                <!-- /.navbar-collapse -->
                            </div>
                        </nav>
                    </div>
                </div>
            </div>
        </div>
    </header>
    <!-- ======= Header Part End ======= -->

    <!-- ======= slider part start ======= -->
    <section id="top" class="slider-area"><br><br><br>
        <div class="container">
            <!-- slider info -->
            <div class="slider-table">
                <div class="slider-table-cell">
                    <h2>Manage Your Estate Assets </h2>
                    <h2>and all of its resources</h2>
                    <p class="cd-headline clip is-full-width">
                        Fully Automated
                        <span class="cd-words-wrapper">
                            <b class="is-visible">State of the art Payment Integrations</b>
                            <b>Utility Management Module</b>
                            <b>Notification System</b>

                        </span>
                    </p>

                    <a class="oxe-btn hvr-shutter-out-horizontal" href="{% url 'auth_login' %}">Login </a>
                    <a class="oxe-btn hvr-shutter-in-horizontal" href="{% url 'user:register' %}">Sign Up</a>
                    <!-- <a class="oxe-btn hvr-shutter-in-horizontal" href="https://clanit.herokuapp.com">Sign Up</a> -->
                    

                </div>
            </div>
            <!-- ======= footer area start ======= -->
                <div class="row">
                    <div class="col-md-8 col-sm-7">
                        <div class="copy-right-text">
                            &copy; copyright Serve Consulting Limited 2018. All Rights Reserved.
                        </div>
                    </div>
                </div>
            <!-- ======= footer area end ======= -->
        </div>
    </section>
    <!-- ======= slider part end ======= -->

    

    <!-- ======= All JS ======= -->
    <!-- modernizr js -->
    <script src="{% static 'site/home_page/js/vendor/modernizr-3.5.0.min.js' %}"></script>
    <!-- jQuery min js -->
    <script src="{% static 'site/home_page/js/vendor/jquery-3.2.1.min.js' %}"></script>
    <!-- bootstrap js -->
    <script src="{% static 'site/home_page/js/bootstrap.min.js' %}"></script>
    <!-- owl carousel js -->
    <script src="{% static 'site/home_page/js/owl.carousel.min.js' %}"></script>
    <!-- vegas js -->
    <script src="{% static 'site/home_page/js/vegas.min.js' %}"></script>
    <!-- typing js -->
    <script src="{% static 'site/home_page/js/typing.js' %}"></script>
    <!-- waypoints js -->
    <script src="{% static 'site/home_page/js/jquery.waypoints.min.js' %}"></script>
    <!-- circle progress js -->
    <script src="{% static 'site/home_page/js/circle-progress.js' %}"></script>
    <!-- isotope js -->
    <script src="{% static 'site/home_page/js/isotope.min.js' %}"></script>
    <!-- jarallax js -->
    <script src="{% static 'site/home_page/js/jarallax.min.js' %}"></script>
    <!-- lightbox js -->
    <script src="{% static 'site/home_page/js/lightbox.min.js' %}"></script>
    <!-- ====== gmap3 js ======= -->
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCq4jmXOSB3mlhBKAmVhWq5BUmFzvwWIsk"></script>
    <script src="{% static 'site/home_page/js/gmap3.min.js' %}"></script>
    <!-- scrollUp js -->
    <script src="{% static 'site/home_page/js/jquery.scrollUp.min.js' %}"></script>
    <!-- plugins js -->
    <script src="{% static 'site/home_page/js/plugins.js' %}"></script>
    <!-- main js -->
    <script src="{% static 'site/home_page/js/main.js' %}"></script>

</body>

</html>