app/site_mgt/urls.py
from django.urls import path
from .views import *

app_name = 'site_mgt'

urlpatterns = [
    path('', home, name='home'),
    path('redirect_user', redirect_user, name='redirect_user'),
    path('estate_manager_dashboard', estate_manager_dashboard, name='estate_manager_dashboard'),
    path('resident_dashboard', tenant_dashboard, name='tenant_dashboard'),
    path('security_dashboard', security_dashboard, name='security_dashboard'),
    path('estate_members', estate_members, name='estate_members'),
    path('visitor_log', visitor_log, name='visitor_log'),
    path('add_member', add_member, name='add_member'),
    path('estate_visitors_log', estate_visitor_log, name='estate_visitor_log'),
    path('profile', profile, name='profile'),
    path('my_buildings', my_buildings, name='my_buildings'),
    path('my_estates', my_estates, name='my_estates'),
    path('my_streets', my_streets, name='my_streets'),
    path('my_apartments', my_apartments, name='my_apartments'),
    path('update_estate/<pk>/edit/', estate_edit, name='update_estate'),
    path('my_estates/<pk>/delete/', delete_estate, name='delete_estate'),
    path('update_street/<pk>/edit/', street_edit, name='update_street'),
    path('update_resident/<pk>/edit/', resident_edit, name='update_resident'),
    path('my_streets/<pk>/delete/', delete_street, name='delete_street'),
    path('update_building/<pk>/edit/', building_edit, name='update_building'),
    path('my_buildings/<pk>/delete/', delete_building, name='delete_building'),
    path('update_apartment/<pk>/edit/', apartment_edit, name='update_apartment'),
    path('my_apartments/<pk>/delete/', delete_apartment, name='delete_apartment'),
    path('estate_members/<pk>/delete/', delete_resident, name='delete_resident'),
    path('add_estate_manager', add_estate_manager, name='add_estate_manager'),
    path('get_details/', get_details, name='get_details'),
    path('get_details_apartment/', get_details_apartment, name='get_details_apartment'),
    path('profile_status/', profile_status, name='profile_status'),
    path('add_street/', add_street, name='add_street'),
    path('get_all_streets/', get_all_streets, name='get_all_streets'),
    path('add_building/', add_building, name='add_building'),
    path('add_apartment/', add_apartment, name='add_apartment'),
    path('userEstateReg/', userEstateReg, name='userEstateReg'),
    path('get_details_build/', get_details_build, name='get_details_build'),
    path('add_residents/', add_residents, name='add_residents'),
    # path('street_dashboard/', street_dashboard, name='street_dashboard'),
    # path('building_dashboard/', building_dashboard, name='building_dashboard'),
    # path('apartment_dashboard/', apartment_dashboard, name='apartment_dashboard'),
    path('salutation/', salutation, name='salutation'),
]

sump/urls.py
from django.contrib import admin
from django.urls import path,include
# This Imports are for serving media files
from django.conf import settings
from django.urls import re_path
from django.views.static import serve
from rest_framework import routers
from api.views import *
from rest_framework.documentation import include_docs_urls

# Routers provide an easy way of automatically determining the URL conf.
router = routers.DefaultRouter()
router.register(r'visitor', VisitorViewSet)
router.register(r'user', UserViewSet)
router.register(r'role', RoleViewSet)
router.register(r'estate', EstateViewSet)
router.register(r'login', LoginUserViewSet, base_name='login')


urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/v1/', include(router.urls)),
    path('acc/', include('app.user.urls')),
    path('', include('app.site_mgt.urls')),
    path('accounts/', include('registration.backends.default.urls')),
    path('api/v1/docs', include_docs_urls(title='Sump Backend API', public=False)),
]

urlpatterns += [
    re_path(
        r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT, }

    ),
]

app/estate_mgt/models.py
from django.db import models
from random import randint, shuffle
from django import forms


def estate_id():
    alpha = ['A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z']
    for i in range(0,20):
        rand_int = randint(0, 9)
        alpha.append(str(rand_int))
    shuffle(alpha)
    return''.join(alpha[0:20])


class Estate(models.Model):
    estate_id = models.CharField(default=estate_id, primary_key=True, max_length=30)
    estate_name = models.CharField(max_length=200)
    estate_address = models.TextField()
    date_created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.estate_name


class Street(models.Model):
    street_id = models.CharField(default=estate_id, primary_key=True, max_length=30)
    estate = models.ForeignKey(Estate, on_delete=models.CASCADE)
    street_name = models.CharField(max_length=250, unique=False)
    date_created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.street_name


class Building(models.Model):
    building_id = models.CharField(default=estate_id, primary_key=True, max_length=30)
    street = models.ForeignKey(Street, on_delete=models.CASCADE)
    building_number = models.CharField(max_length=250, unique=False)
    building_type = models.IntegerField(unique=False, blank=True)
    date_created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.building_number)


class Apartment(models.Model):
    apartment_id = models.CharField(default=estate_id, primary_key=True, max_length=30)
    street = models.ForeignKey(Street, on_delete=models.CASCADE)
    building = models.ForeignKey(Building, on_delete=models.CASCADE)
    apartment_number = models.CharField(max_length=250, unique=False)
    date_created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return 'Apartment: {} {} '.format(self.apartment_id, self.apartment_number)


class Salutation(models.Model):
    title_id = models.CharField(default=estate_id, primary_key=True, max_length=30)
    title_name = models.CharField(max_length=250, unique=True)
    date_created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title_name


class NewEstateForm(forms.ModelForm):
    class Meta:
        model = Estate
        fields = ['estate_id', 'estate_name', 'estate_address']
        widgets = {
            'estate_id': forms.TextInput(attrs={'class': 'form-control', }),
            'estate_name': forms.TextInput(attrs={'class': 'form-control', }),
            'estate_address': forms.TextInput(attrs={'class': 'form-control', })
        }


class NewStreetForm(forms.ModelForm):
    class Meta:
        model = Street
        fields = ['street_id', 'estate', 'street_name']
        widgets = {
            'street_id': forms.TextInput(attrs={'class': 'form-control', }),
            'estate': forms.Select(attrs={'class': 'form-control'}),
            'street_name': forms.TextInput(attrs={'class': 'form-control', })
        }


class NewBuildingForm(forms.ModelForm):
    class Meta:
        model = Building
        fields = ['building_id', 'street', 'building_number', 'building_type']
        widgets = {
            'building_id': forms.TextInput(attrs={'class': 'form-control', }),
            'street': forms.Select(attrs={'class': 'form-control'}),
            'building_number': forms.TextInput(attrs={'class': 'form-control', }),
            'building_type': forms.Select(attrs={'class': 'form-control'}),
        }


class NewApartmentForm(forms.ModelForm):
    class Meta:
        model = Apartment
        fields = ['apartment_id', 'street', 'building', 'apartment_number']
        widgets = {
            'apartment_id': forms.TextInput(attrs={'class': 'form-control', }),
            'street': forms.Select(attrs={'class': 'form-control'}),
            'building': forms.Select(attrs={'class': 'form-control'}),
            'apartment_number': forms.TextInput(attrs={'class': 'form-control', })
        }


class NewSalutationForm(forms.ModelForm):
    class Meta:
        model = Salutation
        fields = ['title_id', 'title_name']
        widgets = {
            'title_id': forms.TextInput(attrs={'class': 'form-control', }),
            'title_name': forms.TextInput(attrs={'class': 'form-control', })
        }

app/user/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from random import randint,shuffle
from django.shortcuts import reverse
from app.estate_mgt.models import Estate

SEX =[['M','Male'],
      ['F','FeMale']]


def user_id():
    alpha = ['A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z']
    for i in range(0,20):
        rand_int = randint(0, 9)
        alpha.append(str(rand_int))
    shuffle(alpha)
    return''.join(alpha[0:20])


def upload_path(instance, filename):
    return instance.get_upload_path(filename)


class RoleManagement(models.Model):
    role_title = models.CharField(max_length=50)

    def __str__(self):
        return self.role_title

    class Meta:
        verbose_name = 'role management'
        verbose_name_plural = 'role management'


class User(AbstractUser):
    user_id = models.CharField(default=user_id, primary_key=True, max_length=30)
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=150)
    role = models.ForeignKey(RoleManagement, on_delete=models.CASCADE, related_name='role',blank=True, null=True)
    image = models.ImageField(upload_to=upload_path, blank=True, null=True)
    email = models.EmailField(unique=True, max_length=75, error_messages={'required': "Email Already Exists"})
    notes = models.TextField(blank=True)
    date_of_birth = models.DateField(blank=True, default="1999-01-01")
    mobile_number = models.BigIntegerField(blank=True, null=True)
    estate = models.ForeignKey(Estate, on_delete=models.CASCADE, null=True)
    address = models.CharField(max_length=200, blank=True)
    flat_number = models.CharField( max_length=20, null=True, blank=True)
    ip_address = models.GenericIPAddressField(blank=True, null=True)
    country = models.CharField(max_length=200, null=True, blank=True)
    country_short = models.CharField(max_length=15, null=True, blank=True)
    state = models.CharField(max_length=200, null=True, blank=True)
    gender = models.CharField(max_length=1, choices=SEX)
    profile_status = models.IntegerField(default=0)


    def get_absolute_url(self):
        return reverse('user:profile', kwargs={'username': self.username})

    def get_upload_path(self,filename):
        return "estate/{}/users/{}/profile_image/{}".format(self.estate,self.username,filename)

    def save(self, *args, **kwargs):

        if not self.pk:
            try:
                if self.gender == 'M':
                    self.image = 'images/male.png'
                elif self.gender == 'F':
                    self.image = 'images/female.png'
            except:
                pass
        else:
            pass
        return super().save(*args, **kwargs)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username']

    def __str__(self):
        return self.username

    class Meta:
        db_table = 'auth_user'
        verbose_name = 'user profile'

templates/site/estate_manager/estate_visitor_log.html
{% extends "site/base.html" %}

{% block content %}
 <div class="row">
                    <div class="col-md-12 widget-holder">
                        <div class="widget-bg">
                            <div class="widget-heading clearfix">
                                <h5>Estate Visitors for {{user.estate}}</h5>
                            </div>
                            <!-- /.widget-heading -->
                            <div class="widget-body clearfix">
                                <table class="table table-striped table-responsive" data-toggle="datatables">
                                    <thead>
                                        <tr>
                                            <th>S/N</th>
                                            <th>Estate Resident Name</th>
                                            <th>Visitors Name</th>
                                            <th>Date Visited</th>

                                        </tr>
                                    </thead>
                                    <tbody>

                                            {% if visitor_log %}
                                            {% for member, count in visitor_log %}
                                            <tr>
                                            <td>{{count}}</td>
                                            <td>{{member.whom_to_see.first_name}} {{member.whom_to_see.last_name}}</td>
                                            <td>{{member.vistor_first_name}} {{member.vistor_last_name}}</td>
                                            <td>{{member.date_created}}</td>
                                            </tr>
                                            {% endfor %}
                                            {% endif %}

                                    </tbody>
                                </table>
                            </div>
                            <!-- /.widget-body -->
                        </div>
                        <!-- /.widget-bg -->
                    </div>
                    <!-- /.widget-holder -->
                </div>
                <!-- /.row -->
{% endblock %}

templates/site/estate_manager/my_apartments.html
{% extends "site/base.html" %}
{% load static %}

{% block content %}
<!--DashBoard Filler-->
            <!-- Page Title Area -->
            <div class="row page-title clearfix">
                <div class="page-title-left">
                    <h6 class="page-title-heading mr-0 mr-r-5">{{user.estate}}</h6>
                    <p class="page-title-description mr-0 d-none d-md-inline-block">| Estate Admin Dashboard</p>
                </div>
                <!-- /.page-title-left -->
                <div class="page-title-right d-none d-sm-inline-flex">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a href="index.html">Dashboard</a>
                        </li>
                        <li class="breadcrumb-item active">Home</li>
                    </ol>
                </div>
                <!-- /.page-title-right -->
            </div>
            <!-- /.page-title -->
            
            <!-- Apartments Table -->
            <div class="col-md-12 widget-holder">
                <div class="widget-bg">
                    <div class="row page-title clearfix">
                        <div class="widget-heading clearfix" align="left">
                            <h5>Apartments</h5>
                        </div>
                        <div class="widget-heading clearfix" align="right">
                            <a href="#" data-toggle="modal" data-target="#create_state"><button class="btn btn-xs btn-primary ripple"><i class="material-icons list-icon">perm_identity</i> <span>Add Apartment</span>
                             </button></a>
                        </div>
                    </div>
                    {%if suc_msg == False %}
                    <div align="center" class="alert alert-danger">
                        <p style="color:crimson !important">Apartment already exists</p>
                    </div>
                    {%endif%}
                    <!-- /.widget-heading -->
                    <div class="widget-body clearfix">
                        <!--<table class="table" data-toggle="table" data-click-to-select="true" data-url="assets/js/bootstrap-table/bootstrap-table.json">-->
                        <table class="table table-editable table-responsive" data-toggle="datatables">
                            <thead>
                                <tr>
                                    <th data-field="state" data-radio="true">S/N</th>
                                    <th data-field="forks_count">Apartment No</th>
                                    <th data-field="stargazers_count">Building No</th>
                                    <th data-field="stargazers_count">Street</th>
                                    <th data-field="forks_count">Estate</th>
                                    <th data-field="forks_count">Action</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% if apartments %}
                                    {%for apartment, count in apartments%}
                                    <tr>
                                        <td>{{count}}</td>
                                        <td>{{apartment.apartment_number}}</td>
                                        <td>{{apartment.building}}</td>
                                        <td>{{apartment.building.street}}</td>
                                        <td>{{apartment.building.street.estate}}</td>
                                        <td style="white-space: nowrap; width: 1%;">
                                            <div class="tabledit-toolbar btn-toolbar" style="text-align: left;">
                                                <div class="btn-group btn-group-sm" style="float: none;">
                                                    <a href="{% url 'site_mgt:update_apartment' pk=apartment.apartment_id %}"><button type="button" class="btn btn-sm btn-primary" style="float: none;"><span class="glyphicon glyphicon-pencil"></span></button></a>
                                                    <a onclick="return confirm_click();" class="del_but" href="{% url 'site_mgt:delete_apartment' pk=apartment.apartment_id %}"><button type="button" class="btn btn-sm btn-danger" style="float: none;"><span class="glyphicon glyphicon-trash"></span></button></a>
                                                </div>
                                            </div>
                                         </td>
                                    </tr>
                                    {% endfor %}
                                {% endif %}
                            </tbody>
                        </table>
                    </div>
                    <!-- /.widget-body -->
                </div>
                <!-- /.widget-bg -->
            </div>
            <!-- /.widget-holder -->
            <hr>

            <!--Modal for Apartment Creation-->
            <div id="create_state" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true" style="display: none">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                        <div class="modal-body">
                            <p align="center">Fill New Apartment Details</p>
                            <form method="POST">
                                <!--{{form3.as_p}}-->
                                {% csrf_token %}
                                <div class="form-group">
                                    <label for="id_street">*STREET</label>
                                    <select name="street" id="id_street" class="form-control" required>
                                        <option value="" selected>Select Street Name</option>
                                    {% for street in all_streets %}
                                        <option value="{{ street.street_id }}"> {{ street.street_name }} </option>
                                    {% endfor %}
                                    </select>
                                </div>
                                <div class="form-group">
                                    <label for="id_building">*BUILDING</label>

                                    <select name="building" class="form-control" required id="id_building">
                                        <!--<option value="" selected>Select Building</option>-->
                                    </select>
                                </div>
                                <div class="form-group" id="apartment_id">
                                    <label for="id_building">*APARTMENT NUMBER</label>
                                     <input class="form-control" type="text" required="" name="apartment_number" id="id_apartment_number">
                                </div>
                                <div class="text-center mr-b-30 btn-list">
                                    <button class="toast-visitor btn btn-rounded btn-success ripple" type="submit" >CREATE APARTMENT</button>
                                </div>
                            </form>
                        </div>
                    </div>
                    <!-- /.modal-content -->
                </div>
                <!-- /.modal-dialog -->
            </div>
            <!-- /.widget-list -->

{% endblock %} 

templates/site/estate_manager/my_buildings.html
{% extends "site/base.html" %}
{% load static %}

{% block content %}
<!--DashBoard Filler-->
            <!-- Page Title Area -->
            <div class="row page-title clearfix">
                <div class="page-title-left">
                    <h6 class="page-title-heading mr-0 mr-r-5">{{user.estate}}</h6>
                    <p class="page-title-description mr-0 d-none d-md-inline-block">| Estate Admin Dashboard</p>
                </div>
                <!-- /.page-title-left -->
                <div class="page-title-right d-none d-sm-inline-flex">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a href="index.html">Dashboard</a>
                        </li>
                        <li class="breadcrumb-item active">Home</li>
                    </ol>
                </div>
                <!-- /.page-title-right -->
            </div>
            <!-- /.page-title -->
            <!-- =================================== -->
            <!-- Building Table -->
            <div class="col-md-12 widget-holder">
                <div class="widget-bg">
                    <div class="row page-title clearfix">
                        <div class="widget-heading clearfix" align="left">
                            <h5>Buildings</h5>
                        </div>
                        <div class="widget-heading clearfix" align="right">
                            <a href="#" data-toggle="modal" data-target="#create_state"><button class="btn btn-xs btn-primary ripple"><i class="material-icons list-icon">perm_identity</i> <span>Add Building</span>
                             </button></a>
                        </div>
                    </div>
                    {%if suc_msg == False %}
                    <div align="center" class="alert alert-danger">
                        <p style="color:crimson !important">Building already exists</p>
                    </div>
                    {%endif%}
                    <!-- /.widget-heading -->
                    <div class="widget-body clearfix">
                        <!--<table class="table" data-toggle="table" data-click-to-select="true" data-url="assets/js/bootstrap-table/bootstrap-table.json">-->
                        <table class="table table-editable table-responsive" data-toggle="datatables">
                            <thead>
                                <tr>
                                    <th data-field="state" data-radio="true">S/N</th>
                                    <th data-field="forks_count">Building No</th>
                                    <th data-field="stargazers_count">Street</th>
                                    <th data-field="stargazers_count">Building Type</th>
                                    <th data-field="stargazers_count">Estate</th>
                                    <th data-field="forks_count">Action</th>
                                </tr>
                            </thead>
                            <tbody>

                                {% if buildings %}
                                    {%for building, count in buildings%}
                                    <tr>
                                        <td>{{count}}</td>
                                        <td>{{building.building_number}}</td>
                                        <td>{{building.street}}</td>
                                        {%if building.building_type == 1%}
                                        <td>Multi Tenancy</td>
                                        {%else%}
                                        <td>Single Tenancy</td>
                                        {%endif%}
                                        <td>{{building.street.estate}}</td>
                                        <td style="white-space: nowrap; width: 1%;">
                                            <div class="tabledit-toolbar btn-toolbar" style="text-align: left;">
                                                <div class="btn-group btn-group-sm" style="float: none;">
                                                    <a href="{% url 'site_mgt:update_building' pk=building.building_id %}"><button type="button" class="btn btn-sm btn-primary" style="float: none;"><span class="glyphicon glyphicon-pencil"></span></button></a>
                                                    <a onclick="return confirm_click();" class="del_but" href="{% url 'site_mgt:delete_building' pk=building.building_id %}"><button type="button" class="btn btn-sm btn-danger" style="float: none;"><span class="glyphicon glyphicon-trash"></span></button></a>
                                                </div>
                                            </div>
                                         </td>
                                    </tr>
                                    {% endfor %}
                                {% endif %}
                            </tbody>
                        </table>
                    </div>
                    <!-- /.widget-body -->
                </div>
                <!-- /.widget-bg -->
            </div>
            <!-- /.widget-holder -->
            <hr>
            <!--Modal for Building Creation-->
            <div id="create_state" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true" style="display: none">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                        <div class="modal-body">
                            {% if all_streets %}
                            <p align="center">Fill New Building Details</p>
                            <form method="POST">{% csrf_token %}
                                <div class="form-group">
                                    <label for="id_street">*STREET</label>
                                    <select name="street" id="id_street" class="form-control" required>
                                        <option value="" selected>Select Street Name</option>
                                    {% for street in all_streets %}
                                        <option value="{{ street.street_id }}"> {{ street.street_name }} </option>
                                    {% endfor %}
                                    </select>
                                </div>
                                <div class="form-group">
                                    <label for="id_building_number">*BUILDING NUMBER</label>
                                     <input class="form-control" type="text" required="" name="building_number" id="id_building_number">
                                </div>
                                <div class="form-group">
                                    <label for="id_building_type">*BUILDING TYPE</label>
                                    <select name="building_type" id="id_building_type" class="form-control" required>
                                        <option value="" selected>Select Building Type</option>
                                        <option value="1">Multi Tenancy</option>
                                        <option value="0">Single Tenancy</option>
                                    </select>
                                </div>

                                <div class="text-center mr-b-30 btn-list">
                                    <button class="toast-visitor btn btn-rounded btn-success ripple" type="submit" >CREATE BUILDING</button>
                                </div>
                            </form>
                            {%else%}
                            <h5 align="center">Please Create A Street First</h5>
                            {% endif %}
                        </div>
                    </div>
                    <!-- /.modal-content -->
                </div>
                <!-- /.modal-dialog -->
            </div>
            <!-- /.widget-list -->

{% endblock %}

templates/site/estate_manager/update_apartment.html
{% extends "site/base.html" %}
{% load static %}

{% block content %}
<!--DashBoard Filler-->
            <!-- Page Title Area -->
            <div class="row page-title clearfix">
                <div class="page-title-left">
                    <h6 class="page-title-heading mr-0 mr-r-5">{{user.estate}}</h6>
                    <p class="page-title-description mr-0 d-none d-md-inline-block">| Estate Admin Dashboard</p>
                </div>
                <!-- /.page-title-left -->
                <div class="page-title-right d-none d-sm-inline-flex">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a href="index.html">Dashboard</a>
                        </li>
                        <li class="breadcrumb-item active">Home</li>
                    </ol>
                </div>
                <!-- /.page-title-right -->
            </div>
            <!-- /.page-title -->
            <!-- =================================== -->
            <form method="POST">
                <!--{{form3.as_p}}-->
                {% csrf_token %}
                <div class="form-group">
                    <label for="id_street">*STREET</label>
                    <select name="street" id="id_street" class="form-control" required>
                            <option value="" selected>Select Street</option>
                    {% for street in all_streets %}
                        <option value="{{ street.street_id }}"> {{ street.street_name }} </option>
                    {% endfor %}
                    </select>
                </div>
                <div class="form-group">
                    <label for="id_building">*BUILDING</label>
                    <select name="building" class="form-control" required id="id_building">
                        <option value="" selected>Select Building</option>
                    </select>
                </div>
                <div class="form-group" id="apartment_id">
                    <label for="id_building">*APARTMENT NUMBER</label>
                        <input class="form-control" type="text" required="" name="apartment_number" id="id_apartment_number" value="{{apartment.apartment_number}}">
                </div>
                <div class="text-center mr-b-30 btn-list">
                    <button class="toast-visitor btn btn-rounded btn-success ripple" type="submit" >SAVE APARTMENT</button>
                </div>
            </form>




{% endblock %}